# dataset/run identifier
sample: 'nwc2_pacbio'

# sequencing technology of input reads (either 'pacbio' or 'nanopore')
technology: 'pacbio'

# directory which contains input reads
read_basepath: 'resources/nwc2/reads' 
# list of read file names to be used
read_filenames: [ 
    "SRR7585901.fastq.gz",
    ]

# CSV-formatted file of: reference-id, reference-fasta-path
ref_csv: 'resources/nwc2/nwc2.references.csv'

# Estimated metagenome size used by flye/canu
mg_size: 8m

# Whether to perform read alignment downsampling or not
subsample: True
# Value of -s option of samtools view for downsampling (used only if 'subsample' is set to True)
subsample_frac: 0.1743

